### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by i8beef** [ruimarinho/docker-z-way#1]
I've been kicking around the idea of Dockerizing Z-Way today as well to eliminate a Pi from my setup. I've looked at all of the images I could find and frankly they all leave a lot of be desired. They all seem to have a PIECE of the Docker story, but none of them are really complete. Yours actually seems to be the best thought out though at least from a Docker configuration perspective, so I have some questions for you if you don't mind.

1. Are you planning on actively maintaining here / turning this into anything more than a hobby project? I wish they'd make official images, but that doesn't look likely...
2. I notice you are only building ubunutu based images. Any thoughts on a rpi docker image, maybe based on the hypriot images? This would be another Dockerfile to maintain, but since you took a fairly good road with your image here, thats probably not major. I haven't worked with travis.ci before so Im not sure what your build pipeline looks like here though. My thought was just to use the Docker Hub automated builds and control it all with repo tags...
3. Looks like you are using the USB stick instead of the Razberry board. It looks like a little extra work is needed to get those to work (see at the end: https://technmeblog.wordpress.com/2015/11/28/running-z-way-on-a-raspberry-pi-in-a-docker-container/). Nothing really for you to do here, just if you supported it in a rpi image, you'd need to expose this in documentation.
3. It looks like you went a very simple route of JUST pulling the Z-Way files and not the mongoose / Webif stuff from the install file. How's that been working for you? Any breakages because of it? It looks like those extra pieces are just there to expose this to the find.zwave.com site stuff, which might be nice for a COMPLETE image, but not something I'd care about if it isn't needed.
4. I notice you aren't exposing any VOLUMEs. What effect does that have on the statefulness of the application?  Are you losing your entire configuration on image rebuild? I haven;t found any definitive docs on where all Z-Way writes files to... /var/log/z-way-server obviously would be a canididate here, but have you have any luck on identifying individual files / directories that could be VOLUME-ized so the Docker container remains stateless? Some of the other images just mount the whole damn /opt or /opt/z-way-server directories which is OBVIOUSLY wrong.

Sorry to bother you but just looking at your image it was clear you had a better understanding of what was involved here, and what constituted good Docker behavior, than most of the others. If you're interested in making this something more than it is and actively maintaining it, I'm happy to help explore some of this and put in PRs...

**Comment by ruimarinho** [comment]
Hi @i8beef.

1. To be honest, I don't plan on actively maintaining this in terms of adding new features or enhancements besides the occasional version bump. I wish an official version would be available as well..

2. I think the recommended way to do this now is using [manifests](https://blog.docker.com/2017/11/multi-arch-all-the-things/). Want to give a try?

3. That's right and thanks for sharing the article. Adding it to the docs would be great.

4. My tests did not show anything broken at all. I did not have a full setup running as my controller was registered with another system but there was nothing noticeable wrong with it.

5. I haven't bothered with persistence but a `VOLUME` directive is not required in order to achieve that. You can always bind mount by using `docker run`.

If you would like to become an active contributor / maintainer of this image I am more than glad to add you to the repository.
